use_frameworks!

target 'Simplify-Swift_Example' do
  pod 'Simplify-Swift', :path => '../'

  target 'Simplify-Swift_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
